USE customers;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT
	SUM(purchase_amount) AS Revenue,
    gender
FROM custom
GROUP BY gender ;

-- Q2. Which customers used a discount but still spent more than the average purchase
-- amount?
SELECT 
	DISTINCT customer_id,
    purchase_amount,
    AVG(purchase_amount) OVER() AS AVG_purchase_amount
FROM custom
WHERE discount_applied = "Yes"
AND purchase_amount > (SELECT AVG(purchase_amount) FROM custom);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
	item_purchased,
    AVG(review_rating) AS avg_review_rating
FROM custom 
GROUP BY item_purchased
ORDER BY avg_review_rating DESC LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
	shipping_type,
    AVG(purchase_amount) AS Avg_purchase_amount
FROM custom
WHERE shipping_type IN ("Standard" , "Express")
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between
-- subscribers and non-subscribers.
SELECT
	subscription_status,
	AVG(purchase_amount) AS Avg_spend,
    SUM(purchase_amount) AS Total_Revnue
FROM custom
GROUP BY subscription_status;
-- --NO BOTH SPEND EQUAL AMOUNT IN AVG 
-- --NO TOTAL REVENUE GENERATED BY SUBSCRIBED IS HALF THT OF NON SUBSCRIBER  

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased AS Product,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
        * 100.0 / COUNT(*),
        2
    ) AS Percentage_of_Purchases
FROM custom
GROUP BY item_purchased
ORDER BY Percentage_of_Purchases DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of
-- previous purchases, and show the count of each segment.
With Customer_type AS (
SELECT customer_id , previous_purchases ,
CASE 
	WHEN previous_purchases = 1 THEN "New"
    WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
    ELSE "Loyal"
    END AS Customer_segment
FROM custom) 
SELECT Customer_segment , COUNT(*) AS Number_of_customer 
FROM Customer_type
GROUP BY Customer_segment;

    -- Q8. What are the top 3 most purchased products within each category?

WITH purchased_products AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS rank_item
    FROM custom
    GROUP BY item_purchased, category
)

SELECT 
    category,
    total_orders,
    item_purchased,
    rank_item
FROM purchased_products
WHERE rank_item < 4;

	
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to
-- subscribe?|
select subscription_status,
count(customer_id) as repeat_buyers
from custom
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? I
SELECT 
	age_group, 
	SUM(purchase_amount) AS Revenue
FROM custom
GROUP BY age_group